### ISSUE TITLE
Mysterious "Error validating application." error

### ISSUE THREAD

**Issue by grahamc** [fmntf/phpadd#4] opened 2011-01-19 23:22 UTC
When executing PHPADD against my symfony application:

$ php build/phpadd/phpadd.php --publish-html cache/build/phpadd.html --bootstrap test/bootstrap.php lib/

[notices, see #3]

Error validating application.
Usage: phpadd [options] /directory/to/scan

Options:
   --skip-protected    skips the scanning of protected methods
   --skip-private      skips the scanning of private methods
   --bootstrap file    includes `file` before the scan

At least one publisher must be given: 
   --publish-html <file>     HTML output
   --publish-xml  <file>     XML output
   --publish-delim <file>    Tab delimited output

**Comment by fmntf** [comment] 2011-02-22 22:21
Grepping "Error validating application" I see that is something from the scanned code.
The problem is that CLI try..catch catches too much ("InvalidArgumentException").

I have to define some PHPADD-specific exception to let everything else go up.

Thank you.

**Comment by fmntf** [comment] 2011-02-22 22:25
Fixed in 6533770bf44e10a4ffba5867e421cbc7702b7081

**Closed as completed by fmntf** 2011-02-22 22:25 UTC
